### ISSUE TITLE
Can't install latest release (2.3.0)

### ISSUE THREAD

**Issue by dprokscha** [andreypopov/node-red-contrib-miio-roborock#38]
Trying to install the latest release (2.3.0), but this leads to the following exception:

```
[error] Error: addMembership EADDRINUSE
    at Socket.addMembership (dgram.js:850:11)
    at /home/nodered/.node-red/node_modules/node-mihome/lib/protocol-aqara.js:48:26
    at Array.forEach (<anonymous>)
    at /home/nodered/.node-red/node_modules/node-mihome/lib/protocol-aqara.js:46:26
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/home/nodered/.node-red/node_modules/node-mihome/lib/protocol-aqara.js:44:38)
    at Socket.emit (events.js:412:35)
    at startListening (dgram.js:172:10)
    at dgram.js:364:7
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

I am using a fresh clean install of Node-RED 2.1.3 and nodejs 14.18.1

**Comment by andreypopov** [comment]
Unknown error, couldn't reproduce it.

**Comment by andreypopov** [comment]
Duplicate for https://github.com/andreypopov/node-red-contrib-miio-roborock/issues/28
