### ISSUE TITLE
"TypeError: Cannot read properties of undefined (reading 'call')"

### ISSUE THREAD

**Issue by bensteUEM** [andreypopov/node-red-contrib-miio-roborock#58]
** Describe issue **
Starting from a few weeks ago i'm unable to send any commands to my s5max which worked for years :)

** Your flow here **
any inject - any action on the robot

** Screens / Logs **
`"TypeError: Cannot read properties of undefined (reading 'call')"`

** Hardware / Software **
  - raspberry 4 
  - node-red-contrib-miio-roborock 2.3.4

**Comment by frogale** [comment]
Same problem here..  Edit: Moved to Valetudo firmware and MQTT...

**Comment by eutervogel** [comment]
Yep, same here.

**Comment by eutervogel** [comment]
any progess on this?

**Comment by AlexPast** [comment]
Restarting the nodered container solved this issue for me.

**Comment by sschuste** [comment]
The issue came out of the blue for me too. I then updated to version 2.4.0, but that didn't help either. Restarting the container: no. Yelling at the flow: no.

This worked: exporting the flow and then deleting it, uninstalling the palette, restarting Node Red, reinstalling the palette, importing the flow, recreating the scenes in HomeKit and a million other clicks and taps. Just works as if nothing had ever happened.

**Comment by andreypopov** [comment]
Could anyone provide log from node-red-log ?

**Comment by Amli2011** [comment]
`13 Oct 10:01:25 - [error] [miio-roborock-command:ce92ce3b.da3848] TypeError: Cannot read property 'call' of undefined
13 Oct 10:01:25 - [error] [miio-roborock-command:ce92ce3b.da3848] TypeError: Cannot read property 'call' of undefined
`
This is what appears in my node-red-log when I press the inject node for the Start function. One line in the log for each activation of  the insert node. The two nodes are unaltered from the example flow. But it is not a new install. This is on version 1.2.2 of the Roboroc node.

I will update to 2.5 now, and report back.

**Comment by Amli2011** [comment]
After updating the node-red-contrib-miio-roborock Node-Red will not start. node-red-log shows:

13 Oct 10:21:27 - [red] Uncaught Exception:
13 Oct 10:21:27 - [error] Error: addMembership EADDRINUSE
    at Socket.addMembership (dgram.js:850:11)
    at /home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/node_modules/node-mihome/lib/protocol-aqara.js:48:26
    at Array.forEach (<anonymous>)
    at /home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/node_modules/node-mihome/lib/protocol-aqara.js:46:26
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-miio-roborock/node_modules/node-mihome/lib/protocol-aqara.js:44:38)
    at Socket.emit (events.js:412:35)
    at startListening (dgram.js:172:10)
    at dgram.js:364:7
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE


Removing the folder with node-red-contrib-miio-roborock (folder located in .node-red/node-modules/) lets me start the rest of the flows.

Other versions in use:

13 Oct 10:25:55 - [info] Node-RED version: v3.0.2
13 Oct 10:25:55 - [info] Node.js  version: v14.21.3
13 Oct 10:25:55 - [info] Linux 6.1.21-v7+ arm LE


UPDATE:
Removing the folder let me start node-red, but not the flows because of missing nodes. Installing the 1.2.2 version with the commands:


cd .node-red/
cd node_modules/
npm i node-red-contrib-miio-roborock@1.2.2


Give me the nodes back, and it is now working. My roborock now starts .

Still on old version, but that will be for another day...
